# The URL the site will be built for
base_url = "https://tinkering.xyz"

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola.
highlight_code = true

# Basic info
title = "Tinkering"
default_language = "en"
generate_rss = true
description = "Come for the Foo, stay for the Bar"

# Theming
theme = "lightspeed"

[extra]
footer_links = [
    {url = "/", name = "Home"},
    {url = "https://github.com/zmitchell", name = "GitHub"},
    {url = "/about/", name = "About"}
]
author = "Zach Mitchell"
zola = false
netlify = false
maintained_with_love = false
