languageCode = "en-us"
title = "Tinkering"
baseurl = "https://tinkering.xyz/"
theme = "hugo-kiera"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false

# Code
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[author]
    name = "Zach Mitchell"
    github = "zmitchell"
    linkedin = "zmitchell22"

[params]
    # Kiera Theme
    tagline = "I just couldn't leave well enough alone"
