languageCode = "en-us"
title = "Tinkering"
baseurl = "https://tinkering.xyz/"
# theme = "hugo-cactus-theme"
theme = "hugo-kiera"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false

# Code
PygmentsCodeFences = true
PygmentsUseClasses = false
PygmentsStyle = "monokai"

[author]
    name = "Zach Mitchell"
    github = "zmitchell"
    linkedin = "zmitchell22"

[params]
    # Cactus Theme
    bio = "Physicist - Programmer - Breaker of Working Things"
    aboutAuthor = "Yeah, I'll fix that eventually"
    name = "Zach Mitchell"
    enableRSS = true
    # Kiera Theme
    tagline = "It was working a second ago, I promise"
