# The URL the site will be built for
base_url = "https://tinkering.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Basic info
title = "Tinkering"
default_language = "en"
generate_rss = true
description = "Come for the X, stay for the Y"

# Theming
theme = "hyde"

[extra]
# Put all your custom variables here
hyde_theme = "theme-base-0d"
hyde_links = [
    {url = "/", name = "Home"},
    {url = "https://github.com/zmitchell", name = "GitHub"},
    {url = "/about/", name = "About"}
]
hyde_sticky = false
