languageCode = "en-us"
title = "Tinkering.xyz"
baseurl = "https://tinkering.xyz/"
theme = "hugo-cactus-theme"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false

# Code
PygmentsCodeFences = true
PygmentsUseClasses = false
PygmentsStyle = "monokai"


[params]
    # Cactus Theme
    bio = "Physicist - Programmer - Breaker of Working Things"
    aboutAuthor = "Yeah, I'll fix that eventually"
    name = "Zach Mitchell"
    enableRSS = true
    
