# The URL the site will be built for
base_url = "https://tinkering.xyz"

# Basic info
title = "Tinkering"
default_language = "en"
generate_feed = true
feed_filename = "rss.xml"
description = "Come for the Foo, stay for the Bar"

# Theming
theme = "lightspeed"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola.
highlight_code = true

[extra]
default_base_url = "https://tinkering.xyz"  # overridden during branch deploys
nav_links = [
    {url = "/", name = "Home"},
    {url = "https://github.com/zmitchell", name = "GitHub"},
    {url = "/about/", name = "About"}
]
author = "Zach Mitchell"
zola = false
netlify = false
maintained_with_love = false
