languageCode = "en-us"
title = "Tinkering"
baseurl = "https://tinkering.xyz/"
theme = "hugo-kiera"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false

# Code
PygmentsCodeFences = true
PygmentsStyle = "manni"
# PygmentsStyle = "monokai"
# PygmentsStyle = "friendly"
# PygmentsStyle = "native"
# PygmentsStyle = "paraiso-dark"

[author]
    name = "Zach Mitchell"
    github = "zmitchell"
    linkedin = "zmitchell22"

[params]
    # Kiera Theme
    tagline = "I just couldn't leave well enough alone"
    ga = "UA-113476578-1"
