version = 1

[install]
zola.pkg-path = "zola"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
cuda-detection = false

[services.preview]
command = "zola serve"
